"""CPU-only YOLOv8-seg inference over images produced by process_service."""

import logging
import os
import time
from functools import lru_cache

import cv2
import numpy as np

from backend.core.config import get_settings
from backend.schemas.inference import (
    BoundingBox,
    Detection,
    InferenceResponse,
    MeasurementSummary,
    SegmentationMask,
)
from backend.services.measurement_service import measure_crack_mask, summarize_measurements
from backend.services.postprocess_service import postprocess_mask

logger = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def _load_model(model_path: str):
    """Load once per process; importing lazily keeps missing-model handling safe."""
    from ultralytics import YOLO

    return YOLO(model_path)


def _safe_processed_path(processed_image_url: str) -> tuple[str, str]:
    """Resolve only URLs generated by the local upload pipeline."""
    settings = get_settings()
    prefix = "/uploads/"
    if not processed_image_url.startswith(prefix):
        raise ValueError("processed_image_url must be an image URL returned by the processing pipeline.")

    filename = os.path.basename(processed_image_url[len(prefix):])
    if not filename or filename != processed_image_url[len(prefix):]:
        raise ValueError("Invalid processed image URL.")

    path = os.path.abspath(os.path.join(settings.upload_dir, filename))
    upload_root = os.path.abspath(settings.upload_dir)
    if os.path.commonpath([path, upload_root]) != upload_root or not os.path.isfile(path):
        raise ValueError("Processed image was not found. Run image processing again.")
    return path, filename


def _color_for_class(class_id: int) -> tuple[int, int, int]:
    # BGR palette for legible, deterministic overlays.
    colors = ((72, 96, 154), (90, 123, 101), (74, 138, 176), (154, 96, 72))
    return colors[class_id % len(colors)]


def run_inference(processed_image_url: str) -> InferenceResponse:
    settings = get_settings()
    model_path = os.path.abspath(settings.model_path)

    # A missing weights file is an expected setup state, not an invented result.
    if not os.path.isfile(model_path):
        return InferenceResponse(
            status="model_not_available",
            message=(
                "Model not available. Add a compatible YOLOv8-seg checkpoint at "
                f"{settings.model_path} or set MODEL_PATH."
            ),
            model_path=settings.model_path,
        )

    image_path, filename = _safe_processed_path(processed_image_url)
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError("Processed image could not be read.")

    try:
        model = _load_model(model_path)
        # Explicitly force CPU for the development laptop target.
        result = model.predict(
            source=image_path,
            device="cpu",
            imgsz=settings.yolo_image_size,
            conf=settings.yolo_confidence_threshold,
            verbose=False,
        )[0]
    except ImportError as exc:
        logger.exception("Ultralytics is not installed")
        return InferenceResponse(
            status="model_not_available",
            message="Model not available. Install the configured Ultralytics dependency to run inference.",
            model_path=settings.model_path,
        )
    except Exception as exc:
        logger.exception("YOLO inference failed")
        raise RuntimeError(f"YOLO inference failed: {exc}") from exc

    overlay = image.copy()
    measurement_overlay = image.copy()
    detections: list[Detection] = []
    measurements = []
    timestamp = int(time.time() * 1000)
    base_name = os.path.splitext(filename)[0]

    # Segmentation models expose masks alongside boxes. A non-seg checkpoint is
    # rejected rather than silently pretending its boxes are segmentations.
    if result.masks is None and result.boxes is not None and len(result.boxes) > 0:
        raise RuntimeError("Configured checkpoint did not return segmentation masks. Use a YOLOv8-seg model.")

    if result.masks is not None and result.boxes is not None:
        masks = result.masks.data.cpu().numpy()
        boxes = result.boxes
        class_names = result.names

        for index, box in enumerate(boxes):
            if index >= len(masks):
                break
            class_id = int(box.cls.item())
            confidence = round(float(box.conf.item()), 4)
            x1, y1, x2, y2 = (round(float(value), 2) for value in box.xyxy[0].tolist())

            binary_mask = (masks[index] > 0.5).astype(np.uint8)
            # Ultralytics usually restores masks to original shape, but resize
            # defensively to guarantee output matches the processed image.
            if binary_mask.shape != image.shape[:2]:
                binary_mask = cv2.resize(binary_mask, (image.shape[1], image.shape[0]), interpolation=cv2.INTER_NEAREST)

            contours, _ = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            if not contours:
                continue
            contour = max(contours, key=cv2.contourArea)
            epsilon = 0.002 * cv2.arcLength(contour, True)
            simplified = cv2.approxPolyDP(contour, epsilon, True).reshape(-1, 2)
            polygon = [[float(x), float(y)] for x, y in simplified]

            mask_filename = f"{timestamp}_mask_{index}_{base_name}.png"
            mask_path = os.path.join(settings.upload_dir, mask_filename)
            cv2.imwrite(mask_path, binary_mask * 255)

            cleaned_mask = postprocess_mask(binary_mask, image.shape[:2])
            cleaned_mask_filename = f"{timestamp}_cleaned_mask_{index}_{base_name}.png"
            cleaned_mask_path = os.path.join(settings.upload_dir, cleaned_mask_filename)
            cv2.imwrite(cleaned_mask_path, cleaned_mask * 255)
            measurement = measure_crack_mask(cleaned_mask)
            measurements.append(measurement)

            color = _color_for_class(class_id)
            overlay[binary_mask.astype(bool)] = (
                0.55 * overlay[binary_mask.astype(bool)] + 0.45 * np.array(color)
            ).astype(np.uint8)
            measurement_overlay[cleaned_mask.astype(bool)] = (
                0.45 * measurement_overlay[cleaned_mask.astype(bool)] + 0.55 * np.array(color)
            ).astype(np.uint8)
            cv2.rectangle(overlay, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)
            cv2.rectangle(measurement_overlay, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)
            label = f"{class_names[class_id]} {confidence:.2f}"
            cv2.putText(overlay, label, (int(x1), max(18, int(y1) - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)
            measurement_label = f"L {measurement.length_px:.1f}px W {measurement.width_px:.1f}px"
            cv2.putText(
                measurement_overlay,
                measurement_label,
                (int(x1), min(image.shape[0] - 8, max(18, int(y2) + 18))),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                color,
                2,
            )

            detections.append(Detection(
                detection_id=index,
                class_id=class_id,
                class_name=str(class_names[class_id]),
                confidence=confidence,
                bounding_box=BoundingBox(x1=x1, y1=y1, x2=x2, y2=y2),
                segmentation_mask=SegmentationMask(
                    polygon=polygon,
                    mask_url=f"/uploads/{mask_filename}",
                    cleaned_mask_url=f"/uploads/{cleaned_mask_filename}",
                ),
                length_px=measurement.length_px,
                width_px=measurement.width_px,
                max_width_px=measurement.max_width_px,
                area_px2=measurement.area_px2,
                orientation_deg=measurement.orientation_deg,
                measurement_unit=measurement.measurement_unit,
                calibrated=measurement.calibrated,
            ))

    overlay_filename = f"{timestamp}_overlay_{base_name}.jpg"
    measurement_overlay_filename = f"{timestamp}_measurement_overlay_{base_name}.jpg"
    cv2.imwrite(os.path.join(settings.upload_dir, overlay_filename), overlay)
    cv2.imwrite(os.path.join(settings.upload_dir, measurement_overlay_filename), measurement_overlay)
    summary = summarize_measurements(measurements)
    return InferenceResponse(
        status="completed",
        message=(f"Inference completed with {len(detections)} detection(s)." if detections else "Inference completed with no detections."),
        model_path=settings.model_path,
        overlay_image_url=f"/uploads/{overlay_filename}",
        measurement_overlay_url=f"/uploads/{measurement_overlay_filename}",
        measurement_summary=MeasurementSummary(**summary),
        detections=detections,
    )
